### ISSUE TITLE
build issue for 5.15.0-1034-raspi 

### ISSUE THREAD

**Issue by karawitan** [pimox/ceph-dkms#1]
Hello,

  I've successfully build the debian packages for ceph-dkms 0.0.2 .
But at install stage, building of the modules fails with:

```
ubuntu@shinwey:/usr/src/ceph-dkms$ sudo dpkg -i ../ceph-dkms_0.0.2_all.deb
Selecting previously unselected package ceph-dkms.
(Reading database ... 151204 files and directories currently installed.)
Preparing to unpack ../ceph-dkms_0.0.2_all.deb ...
Unpacking ceph-dkms (0.0.2) ...
Setting up ceph-dkms (0.0.2) ...
Loading new ceph-dkms-0.0.2 DKMS files...
Building for 5.15.0-1034-raspi
Building initial module for 5.15.0-1034-raspi
ERROR (dkms apport): unable to determine source package for ceph-dkms
Error! Bad return status for module build on kernel: 5.15.0-1034-raspi (aarch64)
Consult /var/lib/dkms/ceph-dkms/0.0.2/build/make.log for more information.
dpkg: error processing package ceph-dkms (--install):
 installed ceph-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 ceph-dkms

ubuntu@shinwey:/usr/src/ceph-dkms$
```

I have attached the logs below
[make.log](https://github.com/pimox/ceph-dkms/files/12217847/make.log)

I'd guess some version mismatch but don't know how to fix it. Any hints greatly appreciated.

**Comment by karawitan** [comment]
Ok, I've succeeded to integrate recent kernel sources, replaced sources below ceph-dkms/src/default-src/ with   torvalds/linux ones.

Build via DKMS is almost perfect, only one error left, 

```
DKMS make.log for ceph-dkms-0.0.2 for kernel 5.15.0-1034-raspi (aarch64)
Wed Aug  2 14:52:53 UTC 2023
make: Entering directory '/usr/src/linux-headers-5.15.0-1034-raspi'
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/ceph_common.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/super.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/drivers/block/rbd.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/messenger.o
/var/lib/dkms/ceph-dkms/0.0.2/build/src/drivers/block/rbd.c: In function ‘do_rbd_remove’:
/var/lib/dkms/ceph-dkms/0.0.2/build/src/drivers/block/rbd.c:7185:17: error: implicit declaration of function ‘blk_set_queue_dying’; did you mean ‘blk_set_queue_depth’? [-Werror=implicit-function-declaration]
 7185 |                 blk_set_queue_dying(rbd_dev->disk->queue);
      |                 ^~~~~~~~~~~~~~~~~~~
      |                 blk_set_queue_depth
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/inode.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/dir.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/msgpool.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/buffer.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/file.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:297: /var/lib/dkms/ceph-dkms/0.0.2/build/src/drivers/block/rbd.o] Error 1
make[1]: *** [scripts/Makefile.build:560: /var/lib/dkms/ceph-dkms/0.0.2/build/src/drivers/block] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/locks.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/addr.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/pagelist.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/ioctl.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/mon_client.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/decode.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/export.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/cls_lock_client.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/osd_client.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/caps.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/osdmap.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/snap.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/crush/crush.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/crush/mapper.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/xattr.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/crush/hash.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/striper.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/debugfs.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/auth.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/auth_none.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/quota.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/io.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/mds_client.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/crypto.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/armor.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/auth_x.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/ceph_strings.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/mdsmap.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/ceph_hash.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/pagevec.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/strings.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/ceph_frag.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/snapshot.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/string_table.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/debugfs.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/util.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/metric.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/messenger_v1.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/messenger_v2.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/cache.o
  CC [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/acl.o
  LD [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/fs/ceph/ceph.o
  LD [M]  /var/lib/dkms/ceph-dkms/0.0.2/build/src/net/ceph/libceph.o
make: *** [Makefile:1914: /var/lib/dkms/ceph-dkms/0.0.2/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.15.0-1034-raspi'
```

Now looking for the relevant patch inside ubuntu kernel sources ...

**Comment by karawitan** [comment]
ok success after applying kernel patches from ubuntu for the kernel.
